#!/bin/sh

set -ex

sudo  $(which pixiecore)  boot --cmdline "\
printk.devkmsg=on \
rancher.password=rancher rancher.autologin=tty1 \
bootcmd=dd,if=/dev/zero,of=/dev/sda,bs=1024,count=1024 \
rancher.state.script=\"/reset-state.sh /dev/sda\" \
rancher.state.dev=LABEL=RANCHER_STATE rancher.state.autoformat=[/dev/sda] rancher.state.formatzero=true \
rancher.system_docker.registry_mirror=${ENGINE_REGISTRY_MIRROR} \
rancher.docker.registry_mirror=${ENGINE_REGISTRY_MIRROR} \
rancher.bootstrap_docker.registry_mirror=${ENGINE_REGISTRY_MIRROR} \
" vmlinuz-* initrd-*

#rancher.debug=true \
#rancher.state.dev=LABEL=RANCHER_STATE rancher.state.autoformat=[/dev/sda] rancher.state.formatzero=true \
#rancher.cloud_init.datasources=[url:https://raw.githubusercontent.com/SvenDowideit/bin-dir/master/cloud-configs/install-rancher-server.sh]
#rancher.services_include.open-vm-tools=true \
#rancher.services_include.zfs=true \
