#!/bin/bash

~/bin/machine -D create --driver vmwarevsphere \
	--vmwarevsphere-username root \
	--vmwarevsphere-password peterpan \
	--vmwarevsphere-network "VM Network" \
	--vmwarevsphere-vcenter 192.168.33.128 \
	--vmwarevsphere-boot2docker-url rancheros.iso \
	--vmwarevsphere-cfgparam guestinfo.hostname=banana \
	--vmwarevsphere-cfgparam guestinfo.rancher.ENVIRONMENT.SVEN=TEST \
	 $@

# --vmwarevsphere-memory-size "2048" \
#	--vmwarevsphere-cloudinit https://raw.githubusercontent.com/RoastLink/roastlink.github.io/master/cloud-config.yml \
#	--vmwarevsphere-cfgparam guestinfo.rancher.config.url=https://raw.githubusercontent.com/RoastLink/roastlink.github.io/master/cloud-config.yml \
